language: python
deploy:
  provider: heroku
  api_key:
    secure: NG8sXKCr5RNFY7N08OAPgGVZv3QnGzrd/QV+0cEYplkq6PWyqAO/aWVenyP2TcvQXFbwfr3WWjRL7/6LHCc7IJOkoWerRRW2/EqqTJ3T1fDcoOMnqCI7XgMbVsxAof5xNnVShoGXwBEU3ttTQHyjOnvBVes/omWCcbYop7OpkFpgtyj6AJZloU0sWRb1QgkVwd8ORtaLJRo6jtpWUqMRo24hi1W2blHwcQARuVtgXkkkhPdcRrmHrV3wwWgoLVxVRPybC4oMpvRoT3wM6Er2Xmy6rlkFlS6HZQfrNNC1fWjcy72ptbcp3Qh7U9m8Gb+9UlDm9xTr/WLvuolSHL6l7zYgGHDB35eQJ2yLE+UWKu6jgjFhr5jyuK6cCaHOG58yAa+DWLfLIkvqkw2vFGepHaxNY0TpjLbiiGvlYzzfipWLlpY+BtSSTdREkRmUNbHAJ+7Kw4Nc4qQsYbZMsqITKDOp+IzDPBodAEyzpQUH5t/3gfACmJPW8F4nFjWcPiirs3KkW7DbMfcl6Dr480GzbxTWhDYSAqNJ+rUUYzwbMy9nkftSKEYD7P4ojy88AnNCxsQW1GY39aj5XcOIPzU2NOF/cLeJ5eleA6lTe58hu2kLaW1mAOZ4BwFpxn4ruFOoTXO3D8vz9gLEVePr5K0zPX7Vax8BNu+fYmWY6cROysc=
  app: intense-ridge-31987
  on:
    repo: SivagiriVisakan/trail-app
    branch: PRODUCTION
script:
  - echo "Attempting to deploy..."