version: "3"
services:
    server:
     image: yandex/clickhouse-server
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     - "9004:9004"
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    redis:
      image: redis
      ports:
        - "6379:6379"
    app:
      build:
        dockerfile: Dockerfile
        context: .
      ports:
        - "5000:5000"