version: "3"
services:
    clickhouse-server:
     image: yandex/clickhouse-server
     hostname: clickhouse-server
     restart: always
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     - "9004:9004"
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
     expose:
      - "9000"
     volumes:
       - "./database_scripts/clickhouse/clickhouse_schema.sql:/docker-entrypoint-initdb.d/3.sql"
    redis:
      image: redis
      ports:
        - "6379:6379"
    app:
      build:
        dockerfile: Dockerfile
        context: .
      links:
        - mysql
        - clickhouse-server
      depends_on:
        - mysql 
        - clickhouse-server
      ports:
        - "5000:5000"
    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_PORT=3306
        - MYSQL_DATABASE=flask_test
        - MYSQL_ROOT_PASSWORD=supersecretpassword
        - MYSQL_PASSWORD=supersecretpassword
      ports:
        - "3306:3306"
      expose:
        - "3306"
      volumes:
        - "./database_scripts/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
        - "./database_scripts/sql/data.sql:/docker-entrypoint-initdb.d/2.sql"
