version: "3"
services:
    server:
     image: yandex/clickhouse-server
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     - "9004:9004"
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    redis:
      image: redis
      ports:
        - "6379:6379"
    app:
      build:
        dockerfile: Dockerfile
        context: .
      links:
        - mysql
      depends_on:
        - mysql 
      ports:
        - "5000:5000"
    mysql:
      image: mysql
      restart: always
      environment:
        - MYSQL_HOST=localhost
        - MYSQL_PORT=3306
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=flask_test
        - MYSQL_USER=root
        - MYSQL_PASSWORD=supersecretpassword
      ports:
        - "3306:3306"
      expose:
        - "3306"
      volumes:
        - "./database_scripts/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
        - "./database_scripts/sql/data.sql:/docker-entrypoint-initdb.d/2.sql"
